services:
  szuru-dan:
    image: ghcr.io/saetron/szuru-dan-docker:latest
    container_name: szuru-dan
    ports:
      - "9000:9000"
    volumes:
      - ./config.ini:/app/config.ini:ro
    restart: unless-stopped
